import params.NodeClassificationHyperbolicParams
import params.SyntheticEuclideanParams
import params.SyntheticHyperbolicParams
import params.ZINCEuclideanParams
import params.ZINCHyperbolicParams
import params.AirportNodeClassificationHyperbolicParams
